### ISSUE TITLE
Duplicate Songs

### ISSUE THREAD

**Issue by 80081** [bhj/react-redux-starter-kit#40]
Played around with this the other day, there wasn't much feedback when a song is added to the queue, I think a pop up confirmation might be better, currently the text just changes colour.  I found that people were adding the same song to the queue multiple times, I think better feedback when the song is added would prevent this, but also there should be some check to make sure the same singer can't add the same song whilst it's already in the queue.

**Comment by bhj** [comment]
> I think better feedback when the song is added would prevent this

Can you elaborate on what you'd like to see? Songs do currently animate (flash and glow) when added.

> there should be some check to make sure the same singer can't add the same song whilst it's already in the queue.

I'm not in favor of preventing duplicate songs in the queue since there can be valid cases for that.

**Comment by 80081** [comment]
Hmm, I didn't notice any flashing, I just noticed the text changed colour, it wasn't obvious to me the first time I used it that the song had been added to the queue, I thought the text changed to indicate that I'd selected the song, I tried long pressing the song looking for some options to add to queue, it was only when I looked at the queue I made the connection.  Just my opinion but I think some form of confirmation would be more obvious, like a popup or toast just confirming the song is added to the queue.

**Comment by 80081** [comment]
On the duplicate song issue, sure there are legitimate reasons to have the same song twice, but surely not for the same singer whilst they still have that song in the queue?  We ended up with multiple instances of the same song for the same singer in the queue by accident.  Would it make sense to prevent adding the same song for same singer, whilst they still have it active in the queue, or at the least prompt to make sure they intended to add it multiple times.

**Comment by bhj** [comment]
> Would it make sense to prevent adding the same song for same singer, whilst they still have it active in the queue

For some users, perhaps, but I don't think it's something that needs to be strictly enforced at this point. Confirmation modals are typically used to confirm operations that are difficult or impossible to undo, but that's not the case with duplicate queue items (they're easy to remove).

>  I just noticed the text changed colour

In normal use with a player running, a "You're up in Xm" banner should also appear when queueing your first song, so hopefully that helps.

Appreciate the feedback! Will keep an eye out for similar issues.
