### ISSUE TITLE
Order change last second

### ISSUE THREAD

**Issue by 80081** [bhj/react-redux-starter-kit#41]
Whilst playing around with this the other day I found that the song order can change right upto the last second, I think this would be annoying if your turn was 10 seconds away then all of a sudden you get bumped because someone adds a song.  I like that the queue prioritises new singers, but maybe it should be modified to not bump the next singer up if there is less than x seconds of the song left.

**Comment by bhj** [comment]
Agreed; I think we can go a step further where if a user is told they are up next, that gets "locked in".

**Comment by bhj** [comment]
@80081 If you're able to test this feature, stop by #dev on Discord and we'll get you set up!
