### ISSUE TITLE
Format preference

### ISSUE THREAD

**Issue by 80081** [bhj/react-redux-starter-kit#42]
I have a collection of MP4 and MP3 + G's.  I prefer MP4's when they are available.  The ability to set preference globally would be good, currently it seems this must be done on individual songs.

**Comment by bhj** [comment]
In the media folder preferences, songs in folders higher in the list get priority, so the best way to achieve this would be to have separate folders for each format. This is also really handy for preferring MP3+G from certain producers over others.
