### ISSUE TITLE
NGINX Reverse proxy with subfolder

### ISSUE THREAD

**Issue by bibitocarlos** [bhj/react-redux-starter-kit#47]
Hi,

I tried to setup karaoke-forever with my nginx proxy, but i get issues with the subpath option, White screen.
 
`location /karaoke {
        proxy_pass     http://192.168.1.11:8090/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Proto $remote_addr;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        }`

In the console :
 '4/23/2022, 7:10:15 PM [verbose] server[280957]:   <-- GET /
4/23/2022, 7:10:15 PM [verbose] server[280957]:   --> GET / 200 2ms 475b'

I think i have to change something in project.config.js, bu dont know how
Any idea ?

**Comment by bhj** [comment]
Hey @bibitocarlos, there is a beta version with subfolder support. If you'd be willing to give it a try and can join the Discord server, I'd love to see if it works for you. Otherwise this should be supported in the next release. Thanks!

**Comment by bibitocarlos** [comment]
Hi,
Is there a branch to pull to try this bêta version or can i use Master ?

**Comment by bhj** [comment]
Thanks for testing this, @bibitocarlos!

For future readers: If you want to serve the app at `/karaoke` for example, you could run the server using `--urlPath /karaoke` and use an nginx config similar to the following, replacing `<your_server_ip>` and `<your_server_port>`:

```
        location /karaoke {
          proxy_pass http://<your_server_ip>:<your_server_port>/karaoke;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Proto $remote_addr;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
        }
```
