### ISSUE TITLE
Control brightness of player background

### ISSUE THREAD

**Issue by al3ph** [bhj/react-redux-starter-kit#54]
Just found you software whilst researching for an overhaul of my own karaoke software I wrote a few years back, and blimey if your's isn't darn close to what I was intending to do. 

Well done! That's saved me a ton of work. 

Of course now I'm going to start politely requesting features that your's doesn't have that mine did :)

Anyway is there a method of reducing the brightness of the background animations ? They are really cool, but a bit distracting, It's be really handy if they could be dimmed down i.e. a brightness slider of some such.

Cheers!

And thanks for writing this software.

**Comment by al3ph** [comment]
I see you can manually control this by editing the PlayerVisuliser.css. So I've found a workaround, but this still might be a useful feature to add.

```
.container {
  position: absolute;
  z-index: -1;
  opacity: 0.4; // overridden here.
}
```

**Comment by bhj** [comment]
Thanks, going ahead and closing but will keep an eye out for similar requests.
