### ISSUE TITLE
Text background doesn't match text

### ISSUE THREAD

**Issue by al3ph** [bhj/react-redux-starter-kit#55]
I'm seeing the lyric text background repeatedly not match the text. I'm guessing this is driven by CDGGraphics module and it's reporting the wrong values ? 

So I'm not sure this is fixable, but I see you've contributed to the repo, so thought this might be of interest.

cheers.

**Comment by al3ph** [comment]
![Screenshot from 2023-02-26 10-50-11](https://user-images.githubusercontent.com/1025756/221406022-1c0a1d5a-1711-4c31-b738-a3fdcbcd8f7c.png)

**Comment by al3ph** [comment]
If I pause playback, and then change the background value, the bounding box corrects itself. So it looks like something isn't syncing with the contentBounds correctly.

**Comment by bhj** [comment]
Hi, first, which browser is this and does it occur in others? When you say "change the background value" can you be more specific? The blur is generated by a `div` with the `backdrop-filter` property, so I'd start by inspecting it to determine if it's the right size.

What I think you're describing (making some change to re-paint the element fixes its filter rendering) sure sounds like a browser issue, but happy to implement a workaround PR if needed!

**Comment by al3ph** [comment]
By background value, I mean the slider that controls the opacity of the the background.

I'm using 

Google Chrome Version 110.0.5481.177 (Official Build) (64-bit) (Linux Ubuntu)

I'll have a go with Firefox when I get the chance, and get back to you, cheers.

**Comment by bhj** [comment]
Assuming this is sorted; can re-open if not!
