### ISSUE TITLE
Better way to get queue options for desktop.

### ISSUE THREAD

**Issue by vinaykapadia** [bhj/react-redux-starter-kit#56]
Right now, to get the song options (make next, info, remove) you have to swipe. Works great for mobile, but not for desktop. Can still swipe, but its kinda awkward to do. Can we add like a three dot menu or something to open/close the options?

Or better yet, a responsive layout where if the screen is large enough, the options show up anyway. There's plenty of room, huge gap between the song info and the star icon:
![image](https://user-images.githubusercontent.com/17637030/227580963-4fad388f-226b-4679-988e-fdcbddd1dc3f.png)

Most users would use mobile anyway, but having a desktop interface for the DJ would help.

**Comment by bhj** [comment]
It's awkward for sure. I can think of a lot of ways the UI would be different for desktops, but it just isn't and probably will never be a design goal given the app's primary use case.

On the other hand, I'm definitely in favor of making better use of tablet-sized displays, though I do think actions like moving or removing a song should remain behind a gesture to prevent errant taps.
