### ISSUE TITLE
[Feature Request] Manual User Management

### ISSUE THREAD

**Issue by Californian** [bhj/react-redux-starter-kit#63]
It would be great to be able to add users as an admin and "impersonate" them so they don't have to go to a URL on their devices (I have some...idiosyncratic friends without phones, or sometimes their phones will be too old for mDNS, some people just don't want to figure out software, etc etc).

(I thought this belonged in a separate issue since the implementation is likely separate.)

**Comment by bhj** [comment]
Interesting! I do wonder if the complexity for supporting this edge case would be worth it, though. IMO it'd be better to put energy toward lowering account creation and sign-in friction (QR codes and passkeys in particular) which would lower barriers for all users.

**Comment by Californian** [comment]
Oh the other circumstance in which this is needed is when a user just hasn't joined the same wifi network, which is a common occurrence with guests in most houses I've gone to and, in particular, my own. Even with QR codes and wifi credentials on the wall.

**Comment by bhj** [comment]
Makes sense. Design-wise we are operating under the assumption that singers have a device with connectivity to the server; other setups are going to be out of scope for the foreseeable future.
