### ISSUE TITLE
Trouble with the player (never shown)

### ISSUE THREAD

**Issue by JerroNIM0** [bhj/react-redux-starter-kit#65]
Hello,
I set up a karaoke using your nice software
It can be accessed from outside (_use of a specific domain name behind nginx_)
All my tests are good (_locally and across the web_)
But my niece (who is in Norway) encounters difficulties because she never displays the player banner whatever the device used (2 recents smartphones, 3 differents PCs) and even when she uses the address (_by adding player instead of queue_) this does not display the player's banner, so she can **never start** the karaoke.
Do you have an idea please?
Regards

**Comment by bhj** [comment]
Hi! Can you clarify what happens when she manually goes to `/player` (the "Start Player" banner won't show if you're already on the player page, but the player should load). Is it a blank page or something else? Any errors in the browser console?

**Comment by JerroNIM0** [comment]
When she click on the middle button in the bottm she enter the room but didn't had the player link (picture KE_01).
When she use /player she goes to the player (picture KE_02) BUT she never saw the controls of the player (picture KE_03) on the top of the browser (in source code the div containing the controls is empty)
Precision if it can help : initially she was a normal user, but i set her as server administrator and now she is able to see (and use) all like a normal situation.
![KE_01](https://github.com/bhj/KaraokeEternal/assets/52593242/4427ff9e-213e-4640-b0bb-e677730bfe00)
![KE_02](https://github.com/bhj/KaraokeEternal/assets/52593242/605839d6-4d5f-44fb-91c6-b85e7368f3d2)
![KE_03](https://github.com/bhj/KaraokeEternal/assets/52593242/7c2f08a0-284b-49fe-a850-d96ae7f16992)

**Comment by bhj** [comment]
Ah thanks, yes, only admins can run a player. It'd be good to redirect non-admins, so I'll look into that.

She's good to go now that she's an admin?

**Comment by JerroNIM0** [comment]
yes all is right now as she is admin :)
